const pokemons = {
  count: 1034,
  next: "http://127.0.0.1:8000/pokemon/?page=2",
  previous: null,
  results: [
    {
      id: 43,
      name: "Bulbasaur",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png",
      img_url_big: "https://img.pokemondb.net/artwork/bulbasaur.jpg",
      types: "GRASS, POISON",
      total: 318,
      hp: 45,
      attack: 49,
      defense: 49,
      sp_atk: 65,
      sp_def: 65,
      speed: 45,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 44,
      name: "Ivysaur",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png",
      img_url_big: "https://img.pokemondb.net/artwork/ivysaur.jpg",
      types: "GRASS, POISON",
      total: 405,
      hp: 60,
      attack: 62,
      defense: 63,
      sp_atk: 80,
      sp_def: 80,
      speed: 60,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 45,
      name: "Venusaur",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/venusaur.png",
      img_url_big: "https://img.pokemondb.net/artwork/venusaur.jpg",
      types: "GRASS, POISON",
      total: 525,
      hp: 80,
      attack: 82,
      defense: 83,
      sp_atk: 100,
      sp_def: 100,
      speed: 80,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 46,
      name: "Venusaur, Mega Venusaur",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/venusaur-mega.png",
      img_url_big: "https://img.pokemondb.net/artwork/venusaur-mega.jpg",
      types: "GRASS, POISON",
      total: 625,
      hp: 80,
      attack: 100,
      defense: 123,
      sp_atk: 122,
      sp_def: 120,
      speed: 80,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 47,
      name: "Charmander",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/charmander.png",
      img_url_big: "https://img.pokemondb.net/artwork/charmander.jpg",
      types: "FIRE,",
      total: 309,
      hp: 39,
      attack: 52,
      defense: 43,
      sp_atk: 60,
      sp_def: 50,
      speed: 65,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 48,
      name: "Charmeleon",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/charmeleon.png",
      img_url_big: "https://img.pokemondb.net/artwork/charmeleon.jpg",
      types: "FIRE,",
      total: 405,
      hp: 58,
      attack: 64,
      defense: 58,
      sp_atk: 80,
      sp_def: 65,
      speed: 80,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 49,
      name: "Charizard",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/charizard.png",
      img_url_big: "https://img.pokemondb.net/artwork/charizard.jpg",
      types: "FIRE, FLYING",
      total: 534,
      hp: 78,
      attack: 84,
      defense: 78,
      sp_atk: 109,
      sp_def: 85,
      speed: 100,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 50,
      name: "Charizard, Mega Charizard X",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-x.png",
      img_url_big: "https://img.pokemondb.net/artwork/charizard-mega-x.jpg",
      types: "FIRE, DRAGON",
      total: 634,
      hp: 78,
      attack: 130,
      defense: 111,
      sp_atk: 130,
      sp_def: 85,
      speed: 100,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 51,
      name: "Charizard, Mega Charizard Y",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/charizard-mega-y.png",
      img_url_big: "https://img.pokemondb.net/artwork/charizard-mega-y.jpg",
      types: "FIRE, FLYING",
      total: 634,
      hp: 78,
      attack: 104,
      defense: 78,
      sp_atk: 159,
      sp_def: 115,
      speed: 100,
      info: null,
      created: null,
      modified: null,
    },
    {
      id: 52,
      name: "Squirtle",
      img_url_small: "https://img.pokemondb.net/sprites/sword-shield/icon/squirtle.png",
      img_url_big: "https://img.pokemondb.net/artwork/squirtle.jpg",
      types: "WATER,",
      total: 314,
      hp: 44,
      attack: 48,
      defense: 65,
      sp_atk: 50,
      sp_def: 64,
      speed: 43,
      info: null,
      created: null,
      modified: null,
    },
  ],
};
// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  pokemons,
};
